### ISSUE TITLE
Feature request: ability to look for a bug in a given branch

### ISSUE THREAD

**Issue by lizrea** [bywatersolutions/find-branches-by-bug#1]
It would be nice to be able to ask this tool to look only at, for example, 21.11.10 branches, and skip over everything else. 

A use case is "cleaning out drax patches once we know the patch is in a deployable package"

**Comment by kylemhall** [comment]
I have modified our slack bywaterbot so we can specify more specific branches. Our tool can accept shortnames like "bywater", "bywater-v22", "bywater-v22.11" and so on. However bywaterbot's regex was truncating anything after and including a hyphen. This should now be fixed!
